---
driver:
  name: vagrant

provisioner:
  client_rb:
    chef_license: accept
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: latest
  channel: stable

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[main::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
