language: node_js
node_js:
  "14"
cache:
  directories:
    - "node_modules"
services:
    - postgresql
before_script:
  - psql -c 'create database nightwatch_test' -U postgres
script:
  - yarn
  - yarn global add typescript
  - tsc
  - yarn api:test
