language: node_js
node_js:
  "10"
cache:
  directories:
    - "node_modules"
services:
    - postgresql
before_script:
  - psql -c 'create database nightwatch' -U postgres
script:
  - yarn
  - yarn global add typescript
  - tsc
  - yarn lint
  - yarn test